### PR TITLE
Explain expected warnings generated when commit changes.

### PR DESCRIPTION
**Pull request by bradleyDean**
When committing a change, a warning message shows up in the terminal, as described in [this issue](https://github.com/OpenBeta/openbeta-graphql/issues/262).

This commit implements the proposed changes to the readme, by supplying the explanatory text.

### CODE REVIEW

**Comment by zichongkao** [comment]
Thanks for helping folks understand these errors. But given https://github.com/OpenBeta/openbeta-graphql/pull/265, this isn't necessary anymore right?

**Comment by bradleyDean** [comment]
> Thanks for helping folks understand these errors. But given #265, this isn't necessary anymore right?

Oh, excellent! Yes, I think this solves the problem. I haven't committed any changes yet (soon hopefully), so I cannot personally confirm that the issue is resolved, but it sure looks to me like #265 should do the trick!

**Comment by musoke** [comment]
Yeah, hopefully this PR isn't necessary now, but let's keep it around until @bradleyDean has a chance to verify.

**Comment by bradleyDean** [comment]
> Yeah, hopefully this PR isn't necessary now, but let's keep it around until @bradleyDean has a chance to verify.

It is totally fine with me if someone else verify's. I won't be able to work on this until Saturday, unfortunately.
If anyone else commits a change and doesn't see the warning, I'm sure that we can close this issue.

**Pull request closed without merging**
