### PR TITLE
Added pino for logging OpenBeta/openbeta-graphql#90

### PR DESCRIPTION
**Pull request by admanny**

### CODE REVIEW

**Comment by admanny** [comment]
Additionally we can integrate https://github.com/pinojs/pino-pretty to format the logs in a more visually appearing way - @vnugent

**Comment by vnugent** [comment]
we're currently running Mongo on our own Kubernetes. Do you have suggestions for a log storage solution?

**Comment by admanny** [comment]
I've used logstash->elasticsearch in the past. But for this use-case I believe a Mongo collection should suffice

**Comment by vnugent** [comment]
does it mean we're pushing the log to the same climb DB?

I'm currently using Logflare free plan to ingest frontend log from Vercel (for occasional troubleshooting).

Could their [BYOB](https://logflare.app/pricing) plan work for us?

**Comment by vnugent** [comment]
@all-contributors add @admanny for code

**Pull request merged**
