### PR TITLE
Add sanitize-html and sanitize area description

### PR DESCRIPTION
**Pull request by Vednus**
Issue [#167](https://github.com/OpenBeta/openbeta-graphql/issues/167)

### CODE REVIEW

**Comment by vnugent** [comment]
@all-contributors add @Vednus for code & ideas

**Comment by vnugent** [comment]
@Vednus just checking to see if you need any help.
FYI I fixed https://github.com/OpenBeta/open-tacos/issues/550 which should make it easier to test edits.

**Comment by Vednus** [comment]
Oh hey, no, or if you want to continue on this, feel free. I just got bogged down in my own app because we had a big competition over the weekend (https://www.pebbleclimbing.com/comps/deadpoint-2023) and there were some features/fixes needed asap.

**Comment by vnugent** [comment]
No worries.  Hope you get those features done soon.  This one can wait.

**Comment by Vednus** [comment]
Finished this one. Added to an already created test to test that sanitizing works.

**Pull request merged**
