### PR TITLE
feat: Ice context

### PR DESCRIPTION
**Pull request by musoke**
This adds basic support for ice climbs with the WI grade scales.

This currently assumes that all contexts use only Winter Ice grades rather than a mix of Alpine Ice and Winter Ice.  This is not the case; the grade scale depends on the local climate.

To enable AI grades in future, the ice grades allowed in most contexts should be an array: `[GradeScales.AI, GradeScales.WI]`.

----

Depends on 

- [x] bump version of sandbag
- [x] update version requirement here

### CODE REVIEW

**Comment by vnugent** [comment]
@musoke @zichongkao can we revisit this PR?

**Comment by musoke** [comment]
Yup.  I was waiting for things to settle with the LCO org and picture rewrite.

**Comment by musoke** [comment]
@actuallyyun, could you take a look at the errors here?  I'm updating the version of sandbag here and getting errors relating to `GradeScales` exports.  I'm wondering if this is related to your changes in https://github.com/OpenBeta/sandbag/pull/106

**Comment by musoke** [comment]
~blocked by https://github.com/OpenBeta/sandbag/issues/123~

**Review by vnugent — APPROVED** [review]

**Pull request merged**
